trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet build
  displayName: 'Build Project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Project'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    appName: 'devopsapivijay'
    package: '$(System.DefaultWorkingDirectory)'